/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.user.service.base;

import com.adjecti.user.model.Himmu;
import com.adjecti.user.service.HimmuLocalService;
import com.adjecti.user.service.HimmuLocalServiceUtil;
import com.adjecti.user.service.persistence.HimmuPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the himmu local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.adjecti.user.service.impl.HimmuLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.adjecti.user.service.impl.HimmuLocalServiceImpl
 * @generated
 */
public abstract class HimmuLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, HimmuLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>HimmuLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>HimmuLocalServiceUtil</code>.
	 */

	/**
	 * Adds the himmu to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect HimmuLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param himmu the himmu
	 * @return the himmu that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Himmu addHimmu(Himmu himmu) {
		himmu.setNew(true);

		return himmuPersistence.update(himmu);
	}

	/**
	 * Creates a new himmu with the primary key. Does not add the himmu to the database.
	 *
	 * @param himmuId the primary key for the new himmu
	 * @return the new himmu
	 */
	@Override
	@Transactional(enabled = false)
	public Himmu createHimmu(long himmuId) {
		return himmuPersistence.create(himmuId);
	}

	/**
	 * Deletes the himmu with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect HimmuLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param himmuId the primary key of the himmu
	 * @return the himmu that was removed
	 * @throws PortalException if a himmu with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Himmu deleteHimmu(long himmuId) throws PortalException {
		return himmuPersistence.remove(himmuId);
	}

	/**
	 * Deletes the himmu from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect HimmuLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param himmu the himmu
	 * @return the himmu that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Himmu deleteHimmu(Himmu himmu) {
		return himmuPersistence.remove(himmu);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return himmuPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Himmu.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return himmuPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.adjecti.user.model.impl.HimmuModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return himmuPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.adjecti.user.model.impl.HimmuModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return himmuPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return himmuPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return himmuPersistence.countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public Himmu fetchHimmu(long himmuId) {
		return himmuPersistence.fetchByPrimaryKey(himmuId);
	}

	/**
	 * Returns the himmu matching the UUID and group.
	 *
	 * @param uuid the himmu's UUID
	 * @param groupId the primary key of the group
	 * @return the matching himmu, or <code>null</code> if a matching himmu could not be found
	 */
	@Override
	public Himmu fetchHimmuByUuidAndGroupId(String uuid, long groupId) {
		return himmuPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the himmu with the primary key.
	 *
	 * @param himmuId the primary key of the himmu
	 * @return the himmu
	 * @throws PortalException if a himmu with the primary key could not be found
	 */
	@Override
	public Himmu getHimmu(long himmuId) throws PortalException {
		return himmuPersistence.findByPrimaryKey(himmuId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(himmuLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Himmu.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("himmuId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(himmuLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Himmu.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("himmuId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(himmuLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Himmu.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("himmuId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<Himmu>() {

				@Override
				public void performAction(Himmu himmu) throws PortalException {
					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, himmu);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(Himmu.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return himmuPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement HimmuLocalServiceImpl#deleteHimmu(Himmu) to avoid orphaned data");
		}

		return himmuLocalService.deleteHimmu((Himmu)persistedModel);
	}

	@Override
	public BasePersistence<Himmu> getBasePersistence() {
		return himmuPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return himmuPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the himmus matching the UUID and company.
	 *
	 * @param uuid the UUID of the himmus
	 * @param companyId the primary key of the company
	 * @return the matching himmus, or an empty list if no matches were found
	 */
	@Override
	public List<Himmu> getHimmusByUuidAndCompanyId(
		String uuid, long companyId) {

		return himmuPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of himmus matching the UUID and company.
	 *
	 * @param uuid the UUID of the himmus
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of himmus
	 * @param end the upper bound of the range of himmus (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching himmus, or an empty list if no matches were found
	 */
	@Override
	public List<Himmu> getHimmusByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<Himmu> orderByComparator) {

		return himmuPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the himmu matching the UUID and group.
	 *
	 * @param uuid the himmu's UUID
	 * @param groupId the primary key of the group
	 * @return the matching himmu
	 * @throws PortalException if a matching himmu could not be found
	 */
	@Override
	public Himmu getHimmuByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return himmuPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the himmus.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.adjecti.user.model.impl.HimmuModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of himmus
	 * @param end the upper bound of the range of himmus (not inclusive)
	 * @return the range of himmus
	 */
	@Override
	public List<Himmu> getHimmus(int start, int end) {
		return himmuPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of himmus.
	 *
	 * @return the number of himmus
	 */
	@Override
	public int getHimmusCount() {
		return himmuPersistence.countAll();
	}

	/**
	 * Updates the himmu in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect HimmuLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param himmu the himmu
	 * @return the himmu that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Himmu updateHimmu(Himmu himmu) {
		return himmuPersistence.update(himmu);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			HimmuLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		himmuLocalService = (HimmuLocalService)aopProxy;

		_setLocalServiceUtilService(himmuLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return HimmuLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Himmu.class;
	}

	protected String getModelClassName() {
		return Himmu.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = himmuPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		HimmuLocalService himmuLocalService) {

		try {
			Field field = HimmuLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, himmuLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected HimmuLocalService himmuLocalService;

	@Reference
	protected HimmuPersistence himmuPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		HimmuLocalServiceBaseImpl.class);

}